---
- name: install nginx
  yum: name=nginx state=latest
  # when: "'{{ ansible_host }}' == '{{ master_ip }}'"

- name: change /usr/share/nginx/html/index.html
  shell: echo '<h1>'{{ ansible_host }}'</h1>' > /usr/share/nginx/html/index.html
  # when: "'{{ ansible_host }}' == '{{ master_ip }}'"

- name: change default port nginx
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  # when: "'{{ ansible_host }}' == '{{ master_ip }}'"

- name: start nginx
  service: name=nginx state=started enabled=yes
  # when: "'{{ ansible_host }}' == '{{ master_ip }}'"

