docker_remove_packages:
  - docker
  - docker-client
  - docker-client-latest
  - docker-common
  - docker-latest
  - docker-latest-logrotate
  - docker-logrotate
  - docker-engine

docker_install_packages:
  - git
  - docker-ce
  - docker-ce-cli
  - containerd.io

